### ISSUE TITLE
Google Tag Manager

### ISSUE THREAD

**Issue by shikhashikz** [shikhashikz/shikhashikz.github.io#10]
Need to include this code in the index.html file 

Website Tracking
Global Site Tag (gtag.js)
This is the Global Site Tag (gtag.js) tracking code for this property. Copy and paste this code as the first item into the <HEAD> of every webpage you want to track. If you already have a Global Site Tag on your page, simply add the config line from the snippet below to your existing Global Site Tag.

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-84084860-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-84084860-1');
</script>

**Comment by nishjeki** [comment]
Fixed with commit 61df8744059717edd5cce356602657efcd109ac3
