### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by shikhashikz** [shikhashikz/shikhashikz.github.io#12]
Eager to have me light up your event as a dynamic keynote speaker or insightful panelist? Let's connect! Just drop me a line at [shikha@shikhashikz.com](mailto:shikha@shikhashikz.com). I can't wait to hear from you!

Ready to Maximize Your Revenue? Let's Talk!
https://calendly.com/shikhapakhide

(Possible that the calendly calendar page appears on the page itself)

**Comment by nishjeki** [comment]
Updated.
