### ISSUE TITLE
Theme Change

### ISSUE THREAD

**Issue by shikhashikz** [shikhashikz/shikhashikz.github.io#13]
This theme need to be adopted- https://wowthemesnet.github.io/affiliates-jekyll-theme/

About Page- I have shared the details on what needs to go in the about section via a separate issue
Contact- I have shared the details on what needs to go in the contact section via a separate issue
Blog- All my present blogs need to be moved to this page. The latest 6 blogs need to be on to the home page as per the theme
Books- In this section all the posts which have been tagged as books need to be represented here
Home Page-
The text in the yellow section- 
Revenue-Centric Marketer: Driving Profitable Growth
I craft strategy with design thinking to customize a marketing plan that propels your brand and supercharges revenue growth.

Text for the Newsletter which is on the right hand side-
Sign up to get my monthly free guide in understanding CEO's challenges and how to address them

On the header, follow buttons should be for Instagram, LinkedIn and WhatsApp
https://www.instagram.com/shikhashikz/
https://www.linkedin.com/in/shikha/
https://whatsapp.com/channel/0029Va6rEsS35fLzfzLYGN3W

There will be a testimonial page too. But at present, we will not make it live.

**Comment by nishjeki** [comment]
Theme changed.  Add individual enhancement
